apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "decentralized-app.fullname" . }}-default-deny
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "decentralized-app.fullname" . }}-allow-api-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "decentralized-app.selectorLabels" . | nindent 6 }}
      component: api
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: {{ .Values.apiService.service.port }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "decentralized-app.fullname" . }}-allow-internal-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  # Allow DNS resolution
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
  # Allow communication between services
  - to:
    - podSelector:
        matchLabels:
          {{- include "decentralized-app.selectorLabels" . | nindent 10 }}