groups:
- name: dapp-kpi-alerts
  rules:
  # API Latency Alert
  - alert: APILatencyTooHigh
    expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 0.25
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "API latency is too high"
      description: "API p95 latency is above 250ms (current value: {{ $value }}s)"

  # API Error Rate Alert
  - alert: APIErrorRateTooHigh
    expr: (sum(rate(http_request_errors_total[5m])) / sum(rate(http_requests_total[5m]))) * 100 > 0.5
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "API error rate is too high"
      description: "API error rate is above 0.5% (current value: {{ $value }}%)"

  # Indexer Lag Alert
  - alert: IndexerLagTooHigh
    expr: indexer_lag_blocks > 2
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Indexer lag is too high"
      description: "Indexer lag is above 2 blocks (current value: {{ $value }} blocks)"

  # IPFS Pin Coverage Alert
  - alert: IPFSPinCoverageTooLow
    expr: ipfs_pin_coverage_percent < 99
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "IPFS pin coverage is too low"
      description: "IPFS pin coverage is below 99% (current value: {{ $value }}%)"

  # Keeper Job Failures Alert
  - alert: KeeperJobsFailing
    expr: increase(keeper_jobs_failed_total[5m]) > 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Keeper jobs are failing"
      description: "Keeper jobs are failing ({{ $value }} failures in the last 5 minutes)"

  # MEV Incidents Alert
  - alert: MEVIncidentsDetected
    expr: increase(mev_incidents_total[5m]) > 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "MEV incidents detected"
      description: "MEV incidents detected ({{ $value }} incidents in the last 5 minutes)"