groups:
- name: dapp-slo-alerts
  rules:
  # API Latency SLO (95th percentile latency should be <= 250ms over 7 days)
  - alert: APILatencyErrorBudgetBurning
    expr: |
      (
        (
          # Fast burn rate (14x) for 1 hour
          (
            histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1h])) by (le)) > 0.25
          ) * (14 * 0.25 / 7)
        )
        or
        (
          # Slow burn rate (7x) for 24 hours
          (
            histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[24h])) by (le)) > 0.25
          ) * (7 * 0.25 / 7)
        )
      ) > 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "API latency SLO error budget is burning"
      description: "API p95 latency is above 250ms, burning error budget at a rate that will exhaust it in {{ $value }} days"

  # Error Rate SLO (error rate should be <= 0.5% over 7 days)
  - alert: APIErrorRateErrorBudgetBurning
    expr: |
      (
        (
          # Fast burn rate (14x) for 1 hour
          (
            (sum(rate(http_request_errors_total[1h])) / sum(rate(http_requests_total[1h]))) * 100 > 0.5
          ) * (14 * 0.5 / 7)
        )
        or
        (
          # Slow burn rate (7x) for 24 hours
          (
            (sum(rate(http_request_errors_total[24h])) / sum(rate(http_requests_total[24h]))) * 100 > 0.5
          ) * (7 * 0.5 / 7)
        )
      ) > 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "API error rate SLO error budget is burning"
      description: "API error rate is above 0.5%, burning error budget at a rate that will exhaust it in {{ $value }} days"

  # Indexer Lag SLO (lag should be <= 2 blocks over 1 day)
  - alert: IndexerLagErrorBudgetBurning
    expr: |
      (
        (
          # Fast burn rate (14x) for 1 hour
          (
            avg(indexer_lag_blocks[1h]) > 2
          ) * (14 * 2 / 1)
        )
        or
        (
          # Slow burn rate (7x) for 24 hours
          (
            avg(indexer_lag_blocks[24h]) > 2
          ) * (7 * 2 / 1)
        )
      ) > 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Indexer lag SLO error budget is burning"
      description: "Indexer lag is above 2 blocks, burning error budget at a rate that will exhaust it in {{ $value }} days"

  # IPFS Pin Coverage SLO (coverage should be >= 99% over 1 day)
  - alert: IPFSPinCoverageErrorBudgetBurning
    expr: |
      (
        (
          # Fast burn rate (14x) for 1 hour
          (
            avg(ipfs_pin_coverage_percent[1h]) < 99
          ) * (14 * (100 - 99) / 1)
        )
        or
        (
          # Slow burn rate (7x) for 24 hours
          (
            avg(ipfs_pin_coverage_percent[24h]) < 99
          ) * (7 * (100 - 99) / 1)
        )
      ) > 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "IPFS pin coverage SLO error budget is burning"
      description: "IPFS pin coverage is below 99%, burning error budget at a rate that will exhaust it in {{ $value }} days"

  # MEV Incidents SLO (incidents should be 0 over 30 days)
  - alert: MEVIncidentsErrorBudgetBurning
    expr: |
      (
        (
          # Fast burn rate (14x) for 1 hour
          (
            sum(rate(mev_incidents_total[1h])) > 0
          ) * (14 * 1 / 30)
        )
        or
        (
          # Slow burn rate (7x) for 24 hours
          (
            sum(rate(mev_incidents_total[24h])) > 0
          ) * (7 * 1 / 30)
        )
      ) > 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "MEV incidents SLO error budget is burning"
      description: "MEV incidents detected, burning error budget at a rate that will exhaust it in {{ $value }} days"