name: Bridge Security Tests

on:
  push:
    branches:
      - main
    paths:
      - 'crates/bridge/**'
      - 'crates/core/src/types.rs'
  pull_request:
    branches:
      - main
    paths:
      - 'crates/bridge/**'
      - 'crates/core/src/types.rs'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run bridge unit tests
      run: |
        cd crates/bridge
        cargo test --lib

    - name: Run bridge integration tests
      run: |
        cd crates/bridge
        cargo test --test bridge_integration

    - name: Run bridge simulation tests
      run: |
        cargo test --test bridge_security_simulation

    - name: Run bridge binary simulation
      run: |
        cd crates/bridge
        cargo run --bin bridge_security_simulation

    - name: Check for compilation warnings
      run: |
        cargo check --workspace --quiet