name: Observability Security Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'crates/core/src/observability.rs'
      - 'crates/core/tests/observability_integration.rs'
      - 'tests/observability_simulation.rs'
      - '.github/workflows/observability-security.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'crates/core/src/observability.rs'
      - 'crates/core/tests/observability_integration.rs'
      - 'tests/observability_simulation.rs'
      - '.github/workflows/observability-security.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.75.0]

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}
        components: clippy, rustfmt

    - name: Cache Cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Check code formatting
      run: cargo fmt --all -- --check

    - name: Run clippy checks
      run: |
        cargo clippy --all-targets --all-features -- -D warnings

    - name: Run unit tests
      run: |
        cargo test --lib observability

    - name: Run integration tests
      run: |
        cargo test --test observability_integration

    - name: Run simulation tests
      run: |
        cargo test --test observability_simulation

    - name: Run binary simulation
      run: |
        cargo run --bin observability_simulation

    - name: Run all observability tests
      run: |
        cargo test observability