name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release-notes:
    name: Generate Release Notes
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Generate release notes
      run: |
        # Generate release notes based on commit history
        echo "## What's Changed" > RELEASE_NOTES.md
        git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> RELEASE_NOTES.md
        echo "" >> RELEASE_NOTES.md
        echo "## Full Changelog" >> RELEASE_NOTES.md
        echo "[Compare Changes](https://github.com/attakdefand/MONDOL-DECENTRALIZED-EXCHANGE/compare/$(git describe --tags --abbrev=0 HEAD^)..$GITHUB_REF_NAME)" >> RELEASE_NOTES.md
    
    - name: Upload release notes
      uses: actions/upload-artifact@v3
      with:
        name: release-notes
        path: RELEASE_NOTES.md

  build-and-sign:
    name: Build and Sign Artifacts
    runs-on: ubuntu-latest
    needs: release-notes
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-registry-release-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build release binaries
      run: |
        cargo build --release --workspace
    
    - name: Install cosign
      run: |
        COSIGN_VERSION="v1.13.1"
        curl -Lo cosign.deb "https://github.com/sigstore/cosign/releases/latest/download/cosign_${COSIGN_VERSION}_linux_amd64.deb"
        sudo dpkg -i cosign.deb
    
    - name: Generate cosign key pair
      run: |
        cosign generate-key-pair
      env:
        COSIGN_PASSWORD: ""
    
    - name: Sign binaries
      run: |
        # Sign all binaries in the target/release directory
        for binary in target/release/*; do
          if [ -f "$binary" ] && [ -x "$binary" ]; then
            cosign sign-blob --key cosign.key "$binary" --output-signature "${binary}.sig"
          fi
        done
    
    - name: Upload signed artifacts
      uses: actions/upload-artifact@v3
      with:
        name: signed-binaries
        path: |
          target/release/*
          !target/release/*.d
          !target/release/*.rlib
          !target/release/deps/
          !target/release/build/
          !target/release/.fingerprint/

  docker-release:
    name: Docker Release
    runs-on: ubuntu-latest
    needs: build-and-sign
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: decentralized-app/app
        tags: |
          type=ref,event=tag
          type=sha,prefix={{branch}}-
    
    - name: Build and push indexer service
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./services/indexer-rs/Dockerfile
        push: true
        tags: decentralized-app/indexer:${{ github.ref_name }}
    
    - name: Build and push API service
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./services/api-rs/Dockerfile
        push: true
        tags: decentralized-app/api:${{ github.ref_name }}
    
    - name: Build and push keepers service
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./services/keepers-rs/Dockerfile
        push: true
        tags: decentralized-app/keepers:${{ github.ref_name }}
    
    - name: Build and push IPFS monitor service
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./services/ipfs-rs/Dockerfile
        push: true
        tags: decentralized-app/ipfs-monitor:${{ github.ref_name }}
    
    - name: Build and push MEV monitor service
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./services/mev-monitor/Dockerfile
        push: true
        tags: decentralized-app/mev-monitor:${{ github.ref_name }}
    
    - name: Build and push AA bundler service
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./services/aa-bundler/Dockerfile
        push: true
        tags: decentralized-app/aa-bundler:${{ github.ref_name }}

  provenance:
    name: Provenance Attestation
    runs-on: ubuntu-latest
    needs: docker-release
    steps:
    - uses: actions/checkout@v3
    
    - name: Install cosign
      run: |
        COSIGN_VERSION="v1.13.1"
        curl -Lo cosign.deb "https://github.com/sigstore/cosign/releases/latest/download/cosign_${COSIGN_VERSION}_linux_amd64.deb"
        sudo dpkg -i cosign.deb
    
    - name: Create provenance attestation
      run: |
        # Create in-toto provenance attestation
        echo "Creating provenance attestation"
        cosign attest --predicate RELEASE_NOTES.md --type slsaprovenance decentralized-app/indexer:${{ github.ref_name }}
        cosign attest --predicate RELEASE_NOTES.md --type slsaprovenance decentralized-app/api:${{ github.ref_name }}
        cosign attest --predicate RELEASE_NOTES.md --type slsaprovenance decentralized-app/keepers:${{ github.ref_name }}
        cosign attest --predicate RELEASE_NOTES.md --type slsaprovenance decentralized-app/ipfs-monitor:${{ github.ref_name }}
        cosign attest --predicate RELEASE_NOTES.md --type slsaprovenance decentralized-app/mev-monitor:${{ github.ref_name }}
        cosign attest --predicate RELEASE_NOTES.md --type slsaprovenance decentralized-app/aa-bundler:${{ github.ref_name }}

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [release-notes, provenance]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download release notes
      uses: actions/download-artifact@v3
      with:
        name: release-notes
    
    - name: Download signed binaries
      uses: actions/download-artifact@v3
      with:
        name: signed-binaries
        path: release-binaries
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: false