name: Release Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: dist/

  provenance:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-artifacts
          path: dist/
      - name: Generate provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: provenance
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: release-artifacts
          path: dist/
      - name: Publish to registry
        run: |
          echo "Publishing to registry"
          # This would publish the artifacts to a registry
